"""
Unit tests for the renderer module (src/renderer.py).

Tests slide processing, static content injection, HTML rendering,
and export functionality without database calls.
"""

import tempfile
from pathlib import Path
from uuid import uuid4

import pytest

import src.renderer as renderer_mod
import src.models as _models
from src.models import IntentTypeInfo
from src.renderer import (
    RenderedSlide,
    inject_static_slides,
    format_speaker_notes,
    render_slide,
    render_deck_from_slides,
    export_html,
    make_deck_filename,
    get_title_slide,
    get_thanks_slide,
    get_section_dividers,
    get_divider_images,
    get_intent_order,
    get_themes,
    _strip_citation_hashes,
    _strip_content_data_hashes,
)


# -----------------------------------------------------------------------------
# Test Fixtures
# -----------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def mock_renderer_init():
    """Populate DB caches with values matching the old hardcoded constants."""
    old_itm = _models.INTENT_TYPE_MAP.copy()
    old_ss = _models.STATIC_SLIDES.copy()
    old_sd = _models.SECTION_DIVIDERS_CACHE[:]
    old_tc = _models.THEMES_CACHE.copy()

    _models.INTENT_TYPE_MAP.clear()
    _models.INTENT_TYPE_MAP.update({
        "title": IntentTypeInfo(slide_type="bullets", require_image=False, sort_order=0, is_generatable=False),
        "problem": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=1, is_generatable=True, suggested_title="The AI Infrastructure Problem", requirements="Explain the problem"),
        "why-postgres": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=2, is_generatable=True),
        "comparison": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=3, is_generatable=True),
        "capabilities": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=4, is_generatable=True),
        "thesis": IntentTypeInfo(slide_type="statement", require_image=False, sort_order=5, is_generatable=True),
        "schema-security": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=6, is_generatable=True),
        "architecture": IntentTypeInfo(slide_type="diagram", require_image=True, sort_order=7, is_generatable=True),
        "what-is-rag": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=8, is_generatable=True),
        "rag-in-postgres": IntentTypeInfo(slide_type="code", require_image=True, sort_order=9, is_generatable=True),
        "advanced-retrieval": IntentTypeInfo(slide_type="split", require_image=False, sort_order=10, is_generatable=True, suggested_title="Beyond Vector Search"),
        "what-is-mcp": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=11, is_generatable=True),
        "mcp-tools": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=12, is_generatable=True),
        "gates": IntentTypeInfo(slide_type="flow", require_image=False, sort_order=13, is_generatable=False),
        "observability": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=14, is_generatable=True),
        "what-we-built": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=15, is_generatable=True),
        "takeaways": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=16, is_generatable=True),
        "thanks": IntentTypeInfo(slide_type="bullets", require_image=False, sort_order=99, is_generatable=False),
    })
    _models.STATIC_SLIDES.clear()
    _models.STATIC_SLIDES.update({
        "title": {
            "intent": "title",
            "title": "Postgres as AI Control Plane",
            "subtitle": "Building RAG + MCP Workflows Inside the Database",
            "speaker": "Payal Singh",
            "job_title": "Senior Database Reliability Engineer",
            "company": "NetApp",
            "company_url": "https://www.netapp.com",
            "event": "Scale23x \u2022 March 2026",
        },
        "thanks": {
            "intent": "thanks",
            "title": "Thank You & Questions",
            "bullets": [
                "GitHub: github.com/payalsingh/scale23x-demo",
                "LinkedIn: linkedin.com/in/payalsingh",
                "Email: payal.singh@netapp.com",
                "Slides: Generated by this very system!",
            ],
            "speaker_notes": "Thank the audience for attending. Open the floor for questions. Mention that the code is available on GitHub.",
        },
        "gates": {
            "intent": "gates",
            "title": "Control Gates & Validation",
            "slide_type": "diagram",
            "bullets": [],
            "content_data": {},
            "speaker_notes": "Every slide passes through a chain of PL/pgSQL validation gates.",
            "image_path": "gate-chain-diagram.png",
            "image_alt": "Gate chain validation pipeline",
        },
    })
    _models.SECTION_DIVIDERS_CACHE.clear()
    _models.SECTION_DIVIDERS_CACHE.extend([
        {"after_intent": "problem", "title": "Why Postgres?", "subtitle": "", "image_filename": "divider_01_why_postgres.png", "sort_order": 1},
        {"after_intent": "capabilities", "title": "The Architecture", "subtitle": "", "image_filename": "divider_02_the_architecture.svg", "sort_order": 2},
        {"after_intent": "architecture", "title": "RAG + MCP Deep Dive", "subtitle": "", "image_filename": "divider_03_rag_mcp_deep_dive.svg", "sort_order": 3},
        {"after_intent": "mcp-tools", "title": "Control & Observability", "subtitle": "", "image_filename": "divider_04_control_observability.svg", "sort_order": 4},
        {"after_intent": "observability", "title": "The Demo", "subtitle": "", "image_filename": "divider_05_the_demo.svg", "sort_order": 5},
    ])
    _models.THEMES_CACHE.clear()
    _models.THEMES_CACHE.update({
        "dark": {"name": "dark", "display_name": "Dark Professional", "css_overrides": "", "is_active": True},
        "postgres": {"name": "postgres", "display_name": "Postgres Brand", "css_overrides": """:root {
            --slide-bg: #2d3748;
            --accent-color: #336791;
            --accent-secondary: #e8792e;
            --divider-bg: linear-gradient(135deg, #336791 0%, #2d5f8a 100%);
            --muted-color: #a0aec0;
        }""", "is_active": True},
    })

    renderer_mod._initialized = True
    yield

    _models.INTENT_TYPE_MAP.clear()
    _models.INTENT_TYPE_MAP.update(old_itm)
    _models.STATIC_SLIDES.clear()
    _models.STATIC_SLIDES.update(old_ss)
    _models.SECTION_DIVIDERS_CACHE.clear()
    _models.SECTION_DIVIDERS_CACHE.extend(old_sd)
    _models.THEMES_CACHE.clear()
    _models.THEMES_CACHE.update(old_tc)
    renderer_mod._initialized = False


@pytest.fixture
def sample_slides():
    """Sample slides as they would come from the database."""
    return [
        {
            "slide_id": str(uuid4()),
            "slide_no": 2,
            "intent": "problem",
            "title": "The AI Infrastructure Problem",
            "bullets": [
                "Database sprawl with multiple systems",
                "Lack of transactional guarantees",
                "Audit and compliance gaps",
            ],
            "speaker_notes": "This slide covers the key challenges organizations face.",
            "citations": [
                {"chunk_id": str(uuid4()), "title": "RAG Overview", "url": "https://example.com"},
            ],
        },
        {
            "slide_id": str(uuid4()),
            "slide_no": 3,
            "intent": "why-postgres",
            "title": "Why Postgres for AI Workloads",
            "bullets": [
                "Mature and battle-tested",
                "Rich extension ecosystem",
                "Single source of truth",
            ],
            "speaker_notes": "Postgres advantages for AI applications.",
            "citations": [],
        },
    ]


@pytest.fixture
def minimal_slide():
    """A minimal slide with required fields only."""
    return {
        "slide_id": str(uuid4()),
        "slide_no": 2,
        "intent": "problem",
        "title": "Test Slide",
        "bullets": ["Bullet 1", "Bullet 2", "Bullet 3"],
        "speaker_notes": None,
        "citations": [],
    }


@pytest.fixture
def full_slide_set():
    """A complete set of slides covering all intents."""
    slides = []
    content_intents = [i for i in get_intent_order() if i not in ("title", "thanks")]
    
    for i, intent in enumerate(content_intents):
        slides.append({
            "slide_id": str(uuid4()),
            "slide_no": i + 2,  # After title
            "intent": intent,
            "title": f"Slide for {intent}",
            "bullets": ["Point 1", "Point 2", "Point 3"],
            "speaker_notes": f"Notes for {intent}",
            "citations": [],
        })
    
    return slides


# -----------------------------------------------------------------------------
# Test RenderedSlide Dataclass
# -----------------------------------------------------------------------------

class TestRenderedSlide:
    """Tests for RenderedSlide dataclass."""
    
    def test_default_values(self):
        """Defaults are set correctly."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes=None,
            citations=[],
        )
        
        assert slide.is_static is False
        assert slide.is_divider is False
        assert slide.is_title is False
        assert slide.is_thanks is False
        assert slide.subtitle is None
    
    def test_all_fields(self):
        """All fields can be set."""
        slide = RenderedSlide(
            slide_no=1,
            intent="title",
            title="My Title",
            bullets=["a", "b"],
            speaker_notes="Notes",
            citations=[{"chunk_id": "123"}],
            is_static=True,
            is_title=True,
            subtitle="Subtitle",
            speaker="Speaker Name",
            event="Event Name",
        )
        
        assert slide.slide_no == 1
        assert slide.intent == "title"
        assert slide.is_title is True
        assert slide.subtitle == "Subtitle"


# -----------------------------------------------------------------------------
# Test inject_static_slides
# -----------------------------------------------------------------------------

class TestInjectStaticSlides:
    """Tests for static slide injection."""
    
    def test_adds_title_slide(self, sample_slides):
        """Title slide is added at the beginning."""
        result = inject_static_slides(sample_slides)
        
        assert result[0].is_title is True
        assert result[0].slide_no == 1
        assert result[0].intent == "title"
        assert "Postgres" in result[0].title
    
    def test_adds_thanks_slide(self, sample_slides):
        """Thanks slide is added at the end."""
        result = inject_static_slides(sample_slides)
        
        last = result[-1]
        assert last.is_thanks is True
        assert last.intent == "thanks"
        assert "Thank" in last.title
    
    def test_adds_section_dividers(self, sample_slides):
        """Section dividers are inserted at correct positions."""
        result = inject_static_slides(sample_slides)
        
        dividers = [s for s in result if s.is_divider]
        # Should have divider after "problem" (in sample_slides)
        assert len(dividers) >= 1
        
        # First divider should be "Why Postgres?"
        divider_titles = [d.title for d in dividers]
        assert "Why Postgres?" in divider_titles
    
    def test_preserves_content_slides(self, sample_slides):
        """Original content slides are preserved."""
        result = inject_static_slides(sample_slides)
        
        content_slides = [s for s in result if not s.is_static and not s.is_divider]
        
        assert len(content_slides) == len(sample_slides)
        
        # Check intents are preserved
        result_intents = {s.intent for s in content_slides}
        expected_intents = {s["intent"] for s in sample_slides}
        assert result_intents == expected_intents
    
    def test_sequential_slide_numbers(self, sample_slides):
        """Slide numbers are sequential starting from 1."""
        result = inject_static_slides(sample_slides)
        
        numbers = [s.slide_no for s in result]
        assert numbers == list(range(1, len(result) + 1))
    
    def test_empty_slides_still_adds_static(self):
        """Empty slide list still adds title and thanks."""
        result = inject_static_slides([])
        
        assert len(result) >= 2  # At least title + thanks
        assert result[0].is_title is True
        assert result[-1].is_thanks is True
    
    def test_full_deck_structure(self, full_slide_set):
        """Complete deck has correct structure with all dividers."""
        result = inject_static_slides(full_slide_set)
        
        # Should have 5 section dividers
        dividers = [s for s in result if s.is_divider]
        assert len(dividers) == 5
        
        # Check divider positions
        divider_titles = [d.title for d in dividers]
        for _, title in get_section_dividers():
            assert title in divider_titles

    def test_inserts_static_gates_slide(self, sample_slides):
        """Non-generatable gates intent is inserted as a static slide with image."""
        result = inject_static_slides(sample_slides)
        gates_slides = [s for s in result if s.intent == "gates"]
        assert len(gates_slides) == 1
        gate = gates_slides[0]
        assert gate.is_static is True
        assert gate.title == "Control Gates & Validation"
        assert gate.image_path == "gate-chain-diagram.png"
        assert gate.slide_type == "diagram"

    def test_static_gates_between_mcp_tools_and_observability(self):
        """Gates static slide appears between mcp-tools and observability."""
        slides = [
            {"intent": "mcp-tools", "title": "MCP", "bullets": ["A"], "slide_type": "code",
             "content_data": None, "citations": [], "speaker_notes": "n"},
            {"intent": "observability", "title": "Obs", "bullets": ["B"], "slide_type": "code",
             "content_data": None, "citations": [], "speaker_notes": "n"},
        ]
        result = inject_static_slides(slides)
        intents = [s.intent for s in result if s.intent not in ("title", "thanks", "divider")]
        assert intents == ["mcp-tools", "gates", "observability"]
    
    def test_handles_jsonb_bullets(self):
        """Handles bullets that might be JSON strings from DB."""
        import json
        slides = [{
            "slide_id": str(uuid4()),
            "slide_no": 2,
            "intent": "problem",
            "title": "Test",
            "bullets": json.dumps(["A", "B", "C"]),  # JSON string
            "speaker_notes": "Notes",
            "citations": json.dumps([]),
        }]
        
        result = inject_static_slides(slides)
        content_slide = [s for s in result if s.intent == "problem"][0]
        
        assert content_slide.bullets == ["A", "B", "C"]
    
    def test_normalizes_doc_title_citations(self):
        """Citations with doc_title key are normalized to include title."""
        slides = [{
            "slide_id": str(uuid4()),
            "slide_no": 2,
            "intent": "problem",
            "title": "Test",
            "bullets": ["A", "B", "C"],
            "speaker_notes": "Notes",
            "citations": [{"chunk_id": "uuid-1", "doc_title": "RAG Overview", "relevance": "..."}],
        }]
        
        result = inject_static_slides(slides)
        content_slide = [s for s in result if s.intent == "problem"][0]
        
        # Citation should now have both doc_title and title
        assert content_slide.citations[0].get("title") == "RAG Overview"
        assert content_slide.citations[0].get("doc_title") == "RAG Overview"

    def test_divider_slides_have_image_path(self, full_slide_set):
        """Divider slides from inject_static_slides have image_path set."""
        result = inject_static_slides(full_slide_set)
        dividers = [s for s in result if s.is_divider]
        divider_images = get_divider_images()

        assert len(dividers) == 5
        for d in dividers:
            assert d.image_path is not None, f"Divider '{d.title}' missing image_path"
            assert d.image_alt is not None, f"Divider '{d.title}' missing image_alt"
            assert d.image_path == divider_images[d.title]

    def test_divider_image_paths_are_filenames(self, full_slide_set):
        """Divider image_path values are bare filenames (not full paths)."""
        result = inject_static_slides(full_slide_set)
        dividers = [s for s in result if s.is_divider]

        for d in dividers:
            assert "/" not in d.image_path, f"Divider image_path should be filename only: {d.image_path}"


# -----------------------------------------------------------------------------
# Test DIVIDER_IMAGES mapping
# -----------------------------------------------------------------------------

class TestDividerImages:
    """Tests for get_divider_images() mapping."""

    def test_covers_all_section_dividers(self):
        """get_divider_images() has an entry for every title in get_section_dividers()."""
        divider_images = get_divider_images()
        for _, title in get_section_dividers():
            assert title in divider_images, f"Missing divider image entry for '{title}'"

    def test_no_extra_entries(self):
        """get_divider_images() has no entries beyond get_section_dividers()."""
        divider_titles = {title for _, title in get_section_dividers()}
        for title in get_divider_images():
            assert title in divider_titles, f"Extra divider image entry: '{title}'"

    def test_all_values_are_filenames(self):
        """All values are simple filenames (no directory separators)."""
        for title, filename in get_divider_images().items():
            assert "/" not in filename, f"Filename for '{title}' should not contain '/'"
            assert filename.endswith((".png", ".svg", ".jpg")), \
                f"Filename for '{title}' should be an image: {filename}"


# -----------------------------------------------------------------------------
# Test format_speaker_notes
# -----------------------------------------------------------------------------

class TestFormatSpeakerNotes:
    """Tests for speaker notes formatting."""
    
    def test_basic_notes(self):
        """Basic notes are preserved."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes="These are the notes.",
            citations=[],
        )
        
        formatted = format_speaker_notes(slide)
        assert "These are the notes." in formatted
    
    def test_with_citations(self):
        """Citations are appended to notes."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes="Main notes here.",
            citations=[
                {"title": "Source 1", "url": "https://example1.com"},
                {"title": "Source 2", "url": "https://example2.com"},
            ],
        )
        
        formatted = format_speaker_notes(slide)
        
        assert "Main notes here." in formatted
        assert "Sources:" in formatted
        assert "Source 1" in formatted
        assert "Source 2" in formatted
        assert "example1.com" in formatted
    
    def test_citations_without_url(self):
        """Citations without URL are handled."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes="Notes",
            citations=[{"title": "Internal Doc"}],  # No URL
        )
        
        formatted = format_speaker_notes(slide)
        assert "Internal Doc" in formatted
    
    def test_empty_notes_with_citations(self):
        """Citations still show with no main notes."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes=None,
            citations=[{"title": "Source", "url": "https://example.com"}],
        )
        
        formatted = format_speaker_notes(slide)
        assert "Source" in formatted
    
    def test_no_notes_no_citations(self):
        """Empty result with no notes or citations."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes=None,
            citations=[],
        )
        
        formatted = format_speaker_notes(slide)
        assert formatted == ""
    
    def test_with_doc_title_key(self):
        """Citations with doc_title key (LLM output format) should work."""
        slide = RenderedSlide(
            slide_no=1,
            intent="test",
            title="Test",
            bullets=[],
            speaker_notes="Notes",
            citations=[{"chunk_id": "uuid-1", "doc_title": "RAG Overview", "relevance": "..."}],
        )
        formatted = format_speaker_notes(slide)
        assert "RAG Overview" in formatted
        assert "Unknown Source" not in formatted
    
    def test_with_both_title_and_doc_title_keys(self):
        """When both title and doc_title exist, doc_title takes precedence."""
        slide = RenderedSlide(
            slide_no=1,
            intent="test",
            title="Test",
            bullets=[],
            speaker_notes="Notes",
            citations=[{"doc_title": "Real Title", "title": "Fallback Title"}],
        )
        formatted = format_speaker_notes(slide)
        assert "Real Title" in formatted


# -----------------------------------------------------------------------------
# Test render_slide
# -----------------------------------------------------------------------------

class TestRenderSlide:
    """Tests for single slide rendering."""
    
    def test_returns_dict(self):
        """Returns template-ready dict."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test Title",
            bullets=["A", "B"],
            speaker_notes="Notes",
            citations=[],
        )
        
        result = render_slide(slide)
        
        assert isinstance(result, dict)
        assert result["slide_no"] == 1
        assert result["title"] == "Test Title"
        assert result["bullets"] == ["A", "B"]
    
    def test_includes_title_metadata(self):
        """Title slide includes extra metadata."""
        slide = RenderedSlide(
            slide_no=1,
            intent="title",
            title="Main Title",
            bullets=[],
            speaker_notes=None,
            citations=[],
            is_title=True,
            subtitle="Subtitle Here",
            speaker="Speaker Name",
            event="Event 2026",
        )
        
        result = render_slide(slide)
        
        assert result["is_title"] is True
        assert result["subtitle"] == "Subtitle Here"
        assert result["speaker"] == "Speaker Name"
        assert result["event"] == "Event 2026"
    
    def test_formats_speaker_notes(self):
        """Speaker notes are formatted."""
        slide = RenderedSlide(
            slide_no=1,
            intent="problem",
            title="Test",
            bullets=[],
            speaker_notes="Original notes.",
            citations=[{"title": "Source", "url": "https://example.com"}],
        )
        
        result = render_slide(slide)
        
        assert "Original notes." in result["speaker_notes"]
        assert "Source" in result["speaker_notes"]


# -----------------------------------------------------------------------------
# Test render_deck_from_slides
# -----------------------------------------------------------------------------

class TestRenderDeckFromSlides:
    """Tests for full deck HTML rendering."""
    
    def test_returns_html_string(self, sample_slides):
        """Returns valid HTML string."""
        html = render_deck_from_slides(sample_slides, "Test Presentation")
        
        assert isinstance(html, str)
        assert "<!DOCTYPE html>" in html
        assert "<html" in html
        assert "</html>" in html
    
    def test_includes_title(self, sample_slides):
        """Presentation title is in HTML."""
        html = render_deck_from_slides(sample_slides, "My Custom Title")
        
        assert "My Custom Title" in html
    
    def test_includes_all_slides(self, sample_slides):
        """All slides are rendered in HTML."""
        html = render_deck_from_slides(sample_slides)
        
        # Check for content from sample slides
        assert "The AI Infrastructure Problem" in html
        assert "Why Postgres for AI Workloads" in html
    
    def test_includes_static_slides(self, sample_slides):
        """Static slides (title, thanks) are in HTML."""
        html = render_deck_from_slides(sample_slides)
        
        assert "Postgres as AI Control Plane" in html
        assert "Thank You" in html
    
    def test_includes_dividers(self, sample_slides):
        """Section dividers are in HTML."""
        html = render_deck_from_slides(sample_slides)
        
        # Should have the "Why Postgres?" divider after problem slide
        assert "divider-slide" in html
    
    def test_includes_speaker_notes(self, sample_slides):
        """Speaker notes are in HTML."""
        html = render_deck_from_slides(sample_slides)
        
        assert "aside" in html
        assert "notes" in html
    
    def test_includes_reveal_js(self, sample_slides):
        """Reveal.js is embedded."""
        html = render_deck_from_slides(sample_slides)
        
        assert "Reveal" in html
        assert "initialize" in html.lower() or "Initialize" in html

    def test_divider_slides_include_image(self, sample_slides):
        """Divider slides in rendered HTML include a divider-bg-img."""
        html = render_deck_from_slides(sample_slides)

        assert "divider-bg-img" in html
        # "Why Postgres?" divider should reference its image
        assert "divider_01_why_postgres.png" in html


# -----------------------------------------------------------------------------
# Test export_html
# -----------------------------------------------------------------------------

class TestExportHtml:
    """Tests for HTML export functionality."""
    
    def test_creates_file(self):
        """File is created at specified path."""
        html = "<html><body>Test</body></html>"
        
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "test.html"
            result = export_html(html, output_path)
            
            assert result == output_path
            assert output_path.exists()
    
    def test_creates_parent_directories(self):
        """Parent directories are created if needed."""
        html = "<html><body>Test</body></html>"
        
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "subdir" / "nested" / "test.html"
            result = export_html(html, output_path)
            
            assert output_path.exists()
    
    def test_writes_content(self):
        """Content is written correctly."""
        html = "<!DOCTYPE html><html><body>Custom Content Here</body></html>"
        
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "output.html"
            export_html(html, output_path)
            
            content = output_path.read_text()
            assert "Custom Content Here" in content
    
    def test_utf8_encoding(self):
        """UTF-8 content is handled correctly."""
        html = "<!DOCTYPE html><html><body>Unicode: é ñ 中文</body></html>"
        
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "output.html"
            export_html(html, output_path)
            
            content = output_path.read_text(encoding="utf-8")
            assert "中文" in content


# -----------------------------------------------------------------------------
# Test Configuration Constants
# -----------------------------------------------------------------------------

class TestConfiguration:
    """Tests for configuration accessors."""
    
    def test_title_slide_structure(self):
        """Title slide has required fields."""
        title_slide = get_title_slide()
        assert "title" in title_slide
        assert "subtitle" in title_slide
        assert "speaker" in title_slide
        assert "event" in title_slide
    
    def test_thanks_slide_structure(self):
        """Thanks slide has required fields."""
        thanks_slide = get_thanks_slide()
        assert "title" in thanks_slide
        assert "bullets" in thanks_slide
        assert len(thanks_slide["bullets"]) > 0
    
    def test_section_dividers_count(self):
        """Correct number of section dividers."""
        assert len(get_section_dividers()) == 5
    
    def test_intent_order_completeness(self):
        """Intent order includes all expected intents."""
        expected = [
            "title", "problem", "why-postgres", "comparison", "capabilities",
            "thesis", "schema-security", "architecture", "what-is-rag",
            "rag-in-postgres", "what-is-mcp", "mcp-tools", "gates",
            "observability", "what-we-built", "takeaways", "thanks"
        ]
        
        intent_order = get_intent_order()
        for intent in expected:
            assert intent in intent_order


# -----------------------------------------------------------------------------
# Integration Tests (without database)
# -----------------------------------------------------------------------------

class TestThemes:
    """Tests for theme support."""

    def test_dark_theme_default(self, sample_slides):
        """Default dark theme renders without theme overrides."""
        html = render_deck_from_slides(sample_slides, theme="dark")
        assert "<!DOCTYPE html>" in html
        # Dark theme has no overrides injected
        assert "#336791" not in html

    def test_postgres_theme_applies(self, sample_slides):
        """Postgres theme injects override CSS variables."""
        html = render_deck_from_slides(sample_slides, theme="postgres")
        assert "#336791" in html  # Postgres blue
        assert "#e8792e" in html  # Postgres orange

    def test_unknown_theme_falls_back_to_dark(self, sample_slides):
        """Unknown theme name falls back to dark (no overrides)."""
        html = render_deck_from_slides(sample_slides, theme="nonexistent")
        assert "<!DOCTYPE html>" in html
        assert "#336791" not in html

    def test_themes_dict_has_required_keys(self):
        """All themes have name and overrides."""
        for theme_name, theme in get_themes().items():
            assert "name" in theme, f"Theme '{theme_name}' missing 'name'"
            assert "overrides" in theme, f"Theme '{theme_name}' missing 'overrides'"


class TestIntegration:
    """Integration tests for complete rendering flow."""
    
    def test_full_render_pipeline(self, full_slide_set):
        """Complete pipeline produces valid output."""
        html = render_deck_from_slides(full_slide_set, "Full Integration Test")
        
        # Check HTML structure
        assert "<!DOCTYPE html>" in html
        assert "<section" in html
        
        # Count slides (approximate - includes static and dividers)
        # Full set has 15 content intents + title + thanks + 5 dividers = 22
        section_count = html.count("<section")
        assert section_count >= 20
    
    def test_empty_deck_renders(self):
        """Empty slide list still produces valid HTML."""
        html = render_deck_from_slides([], "Empty Test")
        
        assert "<!DOCTYPE html>" in html
        # Should have at least title and thanks
        assert "Postgres as AI Control Plane" in html
        assert "Thank You" in html
    
    def test_export_and_verify(self, sample_slides):
        """Export creates valid, readable HTML file."""
        html = render_deck_from_slides(sample_slides, "Export Test")
        
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "deck.html"
            export_html(html, output_path)
            
            # Read back and verify
            content = output_path.read_text()
            assert content == html
            assert len(content) > 1000  # Reasonable size


# =============================================================================
# Test make_deck_filename
# =============================================================================


class TestMakeDeckFilename:
    """Tests for make_deck_filename() -- <date>_<time>_<topic>.html naming."""

    def test_basic_topic(self):
        """Normal topic produces expected slug."""
        from datetime import datetime
        ts = datetime(2026, 2, 8, 14, 30, 52)
        result = make_deck_filename("Postgres as AI Server", timestamp=ts)
        assert result == "20260208_143052_postgres_as_ai_server.html"

    def test_special_characters_stripped(self):
        """Special chars become underscores, collapsed."""
        from datetime import datetime
        ts = datetime(2026, 3, 1, 9, 0, 0)
        result = make_deck_filename("RAG + MCP: A Deep-Dive!", timestamp=ts)
        assert result == "20260301_090000_rag_mcp_a_deep_dive.html"

    def test_ends_with_html(self):
        """Output always ends with .html."""
        result = make_deck_filename("Test")
        assert result.endswith(".html")

    def test_no_leading_trailing_underscores_in_slug(self):
        """Slug portion has no leading/trailing underscores."""
        from datetime import datetime
        ts = datetime(2026, 1, 1, 0, 0, 0)
        result = make_deck_filename("  !!Hello World!!  ", timestamp=ts)
        # The slug should be "hello_world", not "_hello_world_"
        assert "_hello_world.html" in result
        assert "__" not in result

    def test_defaults_to_now(self):
        """Without a timestamp, uses current time (just verify format)."""
        result = make_deck_filename("Quick Test")
        # Should start with YYYYMMDD_HHMMSS
        parts = result.split("_", 2)
        assert len(parts[0]) == 8  # YYYYMMDD
        assert len(parts[1]) == 6  # HHMMSS
        assert parts[0].isdigit()
        assert parts[1].isdigit()


class TestStripCitationHashes:
    """Tests for _strip_citation_hashes helper."""

    def test_removes_single_hash(self):
        result = _strip_citation_hashes(["pgvector does X. [7145eea4]"])
        assert result == ["pgvector does X."]

    def test_removes_multiple_hashes(self):
        result = _strip_citation_hashes(["hybrid search. [bfbd1b21][8e24e3a6]"])
        assert result == ["hybrid search."]

    def test_no_hashes_unchanged(self):
        result = _strip_citation_hashes(["plain bullet with no hash"])
        assert result == ["plain bullet with no hash"]

    def test_empty_list(self):
        assert _strip_citation_hashes([]) == []

    def test_preserves_non_hex_brackets(self):
        result = _strip_citation_hashes(["see [section 1] for details"])
        assert result == ["see [section 1] for details"]

    def test_removes_full_uuid(self):
        result = _strip_citation_hashes(
            ["MCP typed tools. [ad77fde7-a7d3-4a75-80ac-0c62cbb08c09]"]
        )
        assert result == ["MCP typed tools."]

    def test_removes_comma_separated_uuids(self):
        result = _strip_citation_hashes(
            ["Reusable blocks. [ad77fde7-a7d3-4a75-80ac-0c62cbb08c09,4384ed52-1f04-481d-a183-b1477667a684]"]
        )
        assert result == ["Reusable blocks."]

    def test_removes_comma_separated_uuids_with_spaces(self):
        result = _strip_citation_hashes(
            ["Grounding. [9d77e47b-8115-4c9d-a636-c0a17faa0f91, 4384ed52-1f04-481d-a183-b1477667a684]"]
        )
        assert result == ["Grounding."]

    def test_removes_mixed_short_and_full(self):
        result = _strip_citation_hashes(
            ["First. [7145eea4]", "Second. [ad77fde7-a7d3-4a75-80ac-0c62cbb08c09]"]
        )
        assert result == ["First.", "Second."]


class TestStripContentDataHashes:
    """Tests for _strip_content_data_hashes on content_data dicts."""

    def test_strips_explain_bullets(self):
        cd = {"explain_bullets": [
            "MCP exposes typed tools like search_chunks. [ad77fde7]",
            "Each tool wraps a Postgres function. [ad77fde7]",
        ]}
        result = _strip_content_data_hashes(cd)
        assert result["explain_bullets"] == [
            "MCP exposes typed tools like search_chunks.",
            "Each tool wraps a Postgres function.",
        ]

    def test_strips_statement_and_caption(self):
        cd = {"statement": "Postgres owns the loop. [bfbd1b21]", "caption": "flow [8e24e3a6]"}
        result = _strip_content_data_hashes(cd)
        assert result["statement"] == "Postgres owns the loop."
        assert result["caption"] == "flow"

    def test_strips_callouts(self):
        cd = {"callouts": ["Data core [1234abcd]", "Clean callout"]}
        result = _strip_content_data_hashes(cd)
        assert result["callouts"] == ["Data core", "Clean callout"]

    def test_strips_flow_steps(self):
        cd = {"steps": [
            {"label": "Ingest [aabbccdd]", "caption": "load docs [11223344]"},
            {"label": "Search"},
        ]}
        result = _strip_content_data_hashes(cd)
        assert result["steps"][0]["label"] == "Ingest"
        assert result["steps"][0]["caption"] == "load docs"
        assert result["steps"][1]["label"] == "Search"

    def test_empty_dict_unchanged(self):
        assert _strip_content_data_hashes({}) == {}

    def test_none_returns_none(self):
        assert _strip_content_data_hashes(None) is None

    def test_strips_full_uuid_from_explain_bullets(self):
        cd = {"explain_bullets": [
            "MCP exposes typed wrappers around Postgres functions, never raw SQL access. [ad77fde7-a7d3-4a75-80ac-0c62cbb08c09,4384ed52-1f04-481d-a183-b1477667a684]",
            "Tools cover retrieval, gating, and commit flows as reusable building blocks. [ad77fde7-a7d3-4a75-80ac-0c62cbb08c09,7c61832d-3819-44cf-b9dd-aeb1194acb0f]",
        ]}
        result = _strip_content_data_hashes(cd)
        assert result["explain_bullets"] == [
            "MCP exposes typed wrappers around Postgres functions, never raw SQL access.",
            "Tools cover retrieval, gating, and commit flows as reusable building blocks.",
        ]


class TestTemplateIncludeSemanticEquivalence:
    """Verify the template include produces semantically equivalent HTML (not byte-identical)."""

    def test_static_render_produces_valid_html_for_all_slide_types(self):
        """Render a deck with all 6 slide types and verify key HTML elements present."""
        slides = [
            {
                "intent": "thesis",
                "title": "Statement Slide",
                "bullets": [],
                "slide_type": "statement",
                "content_data": {"statement": "Big idea", "subtitle": "Support"},
                "citations": [],
            },
            {
                "intent": "comparison",
                "title": "Split Slide",
                "bullets": [],
                "slide_type": "split",
                "content_data": {
                    "left_title": "Left",
                    "left_items": ["L1"],
                    "right_title": "Right",
                    "right_items": ["R1"],
                },
                "citations": [],
            },
            {
                "intent": "gates",
                "title": "Flow Slide",
                "bullets": [],
                "slide_type": "flow",
                "content_data": {
                    "steps": [
                        {"label": "Step 1", "caption": "First"},
                        {"label": "Step 2", "caption": "Second"},
                    ]
                },
                "citations": [],
            },
            {
                "intent": "rag-in-postgres",
                "title": "Code Slide",
                "bullets": [],
                "slide_type": "code",
                "content_data": {
                    "language": "sql",
                    "code_block": "SELECT 1;",
                    "explain_bullets": ["Does a thing"],
                },
                "citations": [],
            },
            {
                "intent": "architecture",
                "title": "Diagram Slide",
                "bullets": [],
                "slide_type": "diagram",
                "content_data": {
                    "callouts": ["Part A", "Part B"],
                    "caption": "Overview",
                },
                "citations": [],
            },
            {
                "intent": "problem",
                "title": "Bullet Slide",
                "bullets": ["Point 1", "Point 2"],
                "slide_type": "bullets",
                "content_data": None,
                "citations": [],
            },
        ]
        html = render_deck_from_slides(slides, title="Test Deck")

        assert "statement-text" in html
        assert "Big idea" in html
        assert "split-layout" in html
        assert "flow-pipeline" in html
        assert "flow-label" in html
        assert "code-block" in html
        assert "SELECT 1;" in html
        assert "diagram-callout" in html
        assert "Part A" in html
        assert "Point 1" in html

    def test_full_deck_with_db_loaded_static_slides(self):
        """Render a full deck and verify title slide, thanks slide, and section dividers come from DB caches."""
        slides = [
            {"intent": "problem", "title": "Problem Slide", "bullets": ["Issue 1"], "slide_type": "bullets", "content_data": None, "citations": []},
            {"intent": "why-postgres", "title": "Why PG", "bullets": ["Reason 1"], "slide_type": "bullets", "content_data": None, "citations": []},
            {"intent": "capabilities", "title": "Capabilities", "bullets": ["Cap 1"], "slide_type": "bullets", "content_data": None, "citations": []},
            {"intent": "architecture", "title": "Arch", "bullets": ["Comp 1"], "slide_type": "bullets", "content_data": None, "citations": []},
            {"intent": "mcp-tools", "title": "MCP", "bullets": ["Tool 1"], "slide_type": "bullets", "content_data": None, "citations": []},
            {"intent": "observability", "title": "Obs", "bullets": ["Metric 1"], "slide_type": "bullets", "content_data": None, "citations": []},
            {"intent": "takeaways", "title": "Takeaways", "bullets": ["Key 1"], "slide_type": "bullets", "content_data": None, "citations": []},
        ]
        html = render_deck_from_slides(slides, title="Test Deck")

        assert "Postgres as AI Control Plane" in html
        assert "Payal Singh" in html
        assert "Scale23x" in html

        assert "Thank You &amp; Questions" in html or "Thank You & Questions" in html
        assert "github.com/payalsingh/scale23x-demo" in html

        assert "Why Postgres?" in html
        assert "The Architecture" in html
        assert "RAG + MCP Deep Dive" in html or "RAG + MCP" in html
        assert "Control &amp; Observability" in html or "Control & Observability" in html
        assert "The Demo" in html

        assert "dark" in html.lower() or "professional" in html.lower() or "css" in html.lower()

    def test_db_theme_overrides_applied(self):
        """Verify the postgres theme CSS overrides from DB caches appear in rendered HTML."""
        slides = [
            {"intent": "problem", "title": "Slide", "bullets": ["B1"], "slide_type": "bullets", "content_data": None, "citations": []},
        ]
        html = render_deck_from_slides(slides, title="Themed", theme="postgres")

        assert "#336791" in html
        assert "--accent-color" in html
