"""
Unit tests for the live server components.

Tests:
- render_single_slide_html() produces correct HTML fragments
- Divider logic for missing preceding slides
- HTML escaping (autoescape consistency)
- Image path rewriting
- sent_dividers tracking
- run_generation_headless() progress wrapper
- _save_deck_to_output() saves deck on completion
"""

import asyncio
import json
from datetime import datetime, timedelta
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import pytest

import src.renderer as renderer_mod
import src.models as _models
from src.models import IntentTypeInfo
from src.renderer import (
    render_single_slide_html,
    RenderedSlide,
    get_jinja_env,
)
from src.orchestrator import (
    _wrap_node_with_progress,
    run_generation_headless,
    create_initial_state,
)
import src.server as server_mod
from src.server import _save_deck_to_output, _config, sse_clients, slide_stats, _deck_stats_cache, consume_progress


# =============================================================================
# Mock renderer init fixture
# =============================================================================


@pytest.fixture(autouse=True)
def mock_renderer_init():
    """Populate DB caches with values matching the old hardcoded constants."""
    old_itm = _models.INTENT_TYPE_MAP.copy()
    old_ss = _models.STATIC_SLIDES.copy()
    old_sd = _models.SECTION_DIVIDERS_CACHE[:]
    old_tc = _models.THEMES_CACHE.copy()

    _models.INTENT_TYPE_MAP.clear()
    _models.INTENT_TYPE_MAP.update({
        "title": IntentTypeInfo(slide_type="bullets", require_image=False, sort_order=0, is_generatable=False),
        "problem": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=1, is_generatable=True),
        "why-postgres": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=2, is_generatable=True),
        "comparison": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=3, is_generatable=True),
        "capabilities": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=4, is_generatable=True),
        "thesis": IntentTypeInfo(slide_type="statement", require_image=False, sort_order=5, is_generatable=True),
        "schema-security": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=6, is_generatable=True),
        "architecture": IntentTypeInfo(slide_type="diagram", require_image=True, sort_order=7, is_generatable=True),
        "what-is-rag": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=8, is_generatable=True),
        "rag-in-postgres": IntentTypeInfo(slide_type="code", require_image=True, sort_order=9, is_generatable=True),
        "advanced-retrieval": IntentTypeInfo(slide_type="split", require_image=False, sort_order=10, is_generatable=True, suggested_title="Beyond Vector Search"),
        "what-is-mcp": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=11, is_generatable=True),
        "mcp-tools": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=12, is_generatable=True),
        "gates": IntentTypeInfo(slide_type="flow", require_image=False, sort_order=13, is_generatable=False),
        "observability": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=14, is_generatable=True),
        "what-we-built": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=15, is_generatable=True),
        "takeaways": IntentTypeInfo(slide_type="bullets", require_image=True, sort_order=16, is_generatable=True),
        "thanks": IntentTypeInfo(slide_type="bullets", require_image=False, sort_order=99, is_generatable=False),
    })
    _models.STATIC_SLIDES.clear()
    _models.STATIC_SLIDES.update({
        "title": {
            "intent": "title",
            "title": "Postgres as AI Control Plane",
            "subtitle": "Building RAG + MCP Workflows Inside the Database",
            "speaker": "Payal Singh",
            "job_title": "Senior Database Reliability Engineer",
            "company": "NetApp",
            "company_url": "https://www.netapp.com",
            "event": "Scale23x \u2022 March 2026",
        },
        "thanks": {
            "intent": "thanks",
            "title": "Thank You & Questions",
            "bullets": [
                "GitHub: github.com/payalsingh/scale23x-demo",
                "LinkedIn: linkedin.com/in/payalsingh",
                "Email: payal.singh@netapp.com",
                "Slides: Generated by this very system!",
            ],
            "speaker_notes": "Thank the audience for attending. Open the floor for questions. Mention that the code is available on GitHub.",
        },
    })
    _models.SECTION_DIVIDERS_CACHE.clear()
    _models.SECTION_DIVIDERS_CACHE.extend([
        {"after_intent": "problem", "title": "Why Postgres?", "subtitle": "", "image_filename": "divider_01_why_postgres.png", "sort_order": 1},
        {"after_intent": "capabilities", "title": "The Architecture", "subtitle": "", "image_filename": "divider_02_the_architecture.svg", "sort_order": 2},
        {"after_intent": "architecture", "title": "RAG + MCP Deep Dive", "subtitle": "", "image_filename": "divider_03_rag_mcp_deep_dive.svg", "sort_order": 3},
        {"after_intent": "mcp-tools", "title": "Control & Observability", "subtitle": "", "image_filename": "divider_04_control_observability.svg", "sort_order": 4},
        {"after_intent": "observability", "title": "The Demo", "subtitle": "", "image_filename": "divider_05_the_demo.svg", "sort_order": 5},
    ])
    _models.THEMES_CACHE.clear()
    _models.THEMES_CACHE.update({
        "dark": {"name": "dark", "display_name": "Dark Professional", "css_overrides": "", "is_active": True},
        "postgres": {"name": "postgres", "display_name": "Postgres Brand", "css_overrides": """:root {
            --slide-bg: #2d3748;
            --accent-color: #336791;
            --accent-secondary: #e8792e;
            --divider-bg: linear-gradient(135deg, #336791 0%, #2d5f8a 100%);
            --muted-color: #a0aec0;
        }""", "is_active": True},
    })

    renderer_mod._initialized = True
    yield

    _models.INTENT_TYPE_MAP.clear()
    _models.INTENT_TYPE_MAP.update(old_itm)
    _models.STATIC_SLIDES.clear()
    _models.STATIC_SLIDES.update(old_ss)
    _models.SECTION_DIVIDERS_CACHE.clear()
    _models.SECTION_DIVIDERS_CACHE.extend(old_sd)
    _models.THEMES_CACHE.clear()
    _models.THEMES_CACHE.update(old_tc)
    renderer_mod._initialized = False


# =============================================================================
# Test render_single_slide_html
# =============================================================================


class TestRenderSingleSlideHtml:
    """Tests for render_single_slide_html()."""

    def test_produces_section_element(self):
        """HTML output contains <section>."""
        slide = {
            "slide_no": 2,
            "intent": "problem",
            "title": "The Problem",
            "bullets": ["Point 1", "Point 2", "Point 3"],
            "speaker_notes": "Some notes",
            "citations": [],
        }

        html, dividers = render_single_slide_html(slide, set())

        assert "<section" in html
        assert "</section>" in html
        assert "The Problem" in html

    def test_renders_bullets(self):
        """Bullets are rendered in a <ul>."""
        slide = {
            "slide_no": 2,
            "intent": "problem",
            "title": "Test",
            "bullets": ["Alpha", "Beta", "Gamma"],
            "speaker_notes": None,
            "citations": [],
        }

        html, _ = render_single_slide_html(slide, set())

        assert "<ul>" in html
        assert "<li>Alpha</li>" in html
        assert "<li>Beta</li>" in html
        assert "<li>Gamma</li>" in html

    def test_with_divider(self):
        """Divider section precedes content slide when intent triggers one."""
        # "why-postgres" comes after "problem" which has a divider "Why Postgres?"
        slide = {
            "slide_no": 3,
            "intent": "why-postgres",
            "title": "Why Postgres for AI",
            "bullets": ["Mature", "Extensions", "Single source"],
            "speaker_notes": None,
            "citations": [],
        }

        html, dividers = render_single_slide_html(slide, set())

        # Should include the "Why Postgres?" divider
        assert "Why Postgres?" in html
        assert "divider-slide" in html
        # And the content slide
        assert "Why Postgres for AI" in html
        # Divider should be tracked
        assert "Why Postgres?" in dividers

    def test_missing_preceding_slide_includes_divider(self):
        """If 'problem' was never committed, 'why-postgres' still gets the divider."""
        slide = {
            "slide_no": 2,
            "intent": "why-postgres",
            "title": "Why PG",
            "bullets": ["A"],
            "speaker_notes": None,
            "citations": [],
        }

        html, dividers = render_single_slide_html(slide, set())

        # Divider after "problem" should still be included
        assert "Why Postgres?" in html
        assert "Why Postgres?" in dividers

    def test_escapes_special_chars(self):
        """Title with <script> is escaped (autoescape consistency)."""
        slide = {
            "slide_no": 2,
            "intent": "problem",
            "title": '<script>alert("xss")</script>',
            "bullets": ["<b>bold</b>"],
            "speaker_notes": None,
            "citations": [],
        }

        html, _ = render_single_slide_html(slide, set())

        # Should NOT contain raw script tag
        assert "<script>alert" not in html
        # Should be escaped
        assert "&lt;script&gt;" in html
        assert "&lt;b&gt;bold&lt;/b&gt;" in html

    def test_image_path_rewritten(self, tmp_path):
        """DB storage_path becomes /images/filename."""
        # Create a fake image file
        img_dir = Path("content/images")
        img_dir.mkdir(parents=True, exist_ok=True)
        test_img = img_dir / "test_rewrite_image.svg"
        test_img.write_text("<svg></svg>")

        try:
            slide = {
                "slide_no": 2,
                "intent": "problem",
                "title": "With Image",
                "bullets": ["A"],
                "speaker_notes": None,
                "citations": [],
                "image_path": "test_rewrite_image.svg",
                "image_alt": "Test diagram",
            }

            html, _ = render_single_slide_html(slide, set())

            assert '/images/test_rewrite_image.svg' in html
            assert 'with-image' in html
        finally:
            test_img.unlink(missing_ok=True)

    def test_sent_dividers_tracking(self):
        """sent_dividers set is updated and prevents re-sending."""
        slide1 = {
            "slide_no": 3,
            "intent": "why-postgres",
            "title": "Why PG",
            "bullets": ["A"],
            "speaker_notes": None,
            "citations": [],
        }

        html1, dividers = render_single_slide_html(slide1, set())
        assert "Why Postgres?" in dividers

        # Second slide in same section -- divider should NOT repeat
        slide2 = {
            "slide_no": 4,
            "intent": "comparison",
            "title": "Comparison",
            "bullets": ["B"],
            "speaker_notes": None,
            "citations": [],
        }

        html2, dividers = render_single_slide_html(slide2, dividers)

        # "Why Postgres?" divider should NOT appear again
        assert html2.count("Why Postgres?") == 0

    def test_jsonb_bullets(self):
        """Handles bullets that are JSON strings from DB."""
        slide = {
            "slide_no": 2,
            "intent": "problem",
            "title": "Test",
            "bullets": json.dumps(["X", "Y", "Z"]),
            "speaker_notes": None,
            "citations": json.dumps([]),
        }

        html, _ = render_single_slide_html(slide, set())

        assert "<li>X</li>" in html
        assert "<li>Y</li>" in html

    def test_normalizes_doc_title_citations(self):
        """Citations with doc_title key get title normalized."""
        slide = {
            "slide_no": 2,
            "intent": "problem",
            "title": "Test",
            "bullets": ["A"],
            "speaker_notes": None,
            "citations": [{"chunk_id": "uuid-1", "doc_title": "RAG Overview"}],
        }

        # Should not raise
        html, _ = render_single_slide_html(slide, set())
        assert "<section" in html

    def test_slide_fragment_includes_data_attributes(self):
        """Generated slide HTML includes data-slide-no and data-intent attributes."""
        slide = {
            "slide_no": 5,
            "intent": "architecture",
            "title": "System Architecture",
            "bullets": ["Components"],
            "speaker_notes": None,
            "citations": [],
        }

        html, _ = render_single_slide_html(slide, set())

        assert 'data-slide-no="5"' in html
        assert 'data-intent="architecture"' in html

    def test_late_intent_includes_all_preceding_dividers(self):
        """A late intent includes all preceding unsent dividers."""
        # "what-is-rag" comes after dividers for "problem", "capabilities", "architecture"
        slide = {
            "slide_no": 5,
            "intent": "what-is-rag",
            "title": "What Is RAG",
            "bullets": ["A"],
            "speaker_notes": None,
            "citations": [],
        }

        html, dividers = render_single_slide_html(slide, set())

        # Should include all dividers before "what-is-rag"
        assert "Why Postgres?" in html
        assert "The Architecture" in html
        assert "RAG + MCP Deep Dive" in html
        assert len(dividers) == 3

    def test_divider_includes_image(self):
        """Divider fragment includes a divider-bg-img with correct path."""
        slide = {
            "slide_no": 3,
            "intent": "why-postgres",
            "title": "Why PG",
            "bullets": ["A"],
            "speaker_notes": None,
            "citations": [],
        }

        html, dividers = render_single_slide_html(slide, set())

        # Divider should include the image
        assert "divider-bg-img" in html
        assert "/images/divider_01_why_postgres.png" in html
        assert 'alt="Section: Why Postgres?"' in html

    def test_divider_image_uses_url_prefix(self):
        """Divider image path uses the image_url_prefix argument."""
        slide = {
            "slide_no": 3,
            "intent": "why-postgres",
            "title": "Why PG",
            "bullets": ["A"],
            "speaker_notes": None,
            "citations": [],
        }

        html, _ = render_single_slide_html(slide, set(), image_url_prefix="/static/img")

        assert "/static/img/divider_01_why_postgres.png" in html


# =============================================================================
# Test progress wrapper
# =============================================================================


class TestWrapNodeWithProgress:
    """Tests for _wrap_node_with_progress()."""

    @staticmethod
    def _make_node_spec(node_fn):
        """Create a mock StateNodeSpec with a RunnableCallable wrapping node_fn."""
        from types import SimpleNamespace
        from langgraph._internal._runnable import RunnableCallable

        runnable = RunnableCallable(func=node_fn, afunc=node_fn)
        return SimpleNamespace(
            runnable=runnable,
            ends=(),
            cache_policy=None,
            defer=False,
            retry_policy=None,
            metadata=None,
            input_schema=None,
        )

    @pytest.mark.asyncio
    async def test_pushes_progress_event(self):
        """Wrapper pushes progress event before executing node."""
        queue = asyncio.Queue()

        async def mock_node(state):
            return {**state, "result": True}

        node_spec = self._make_node_spec(mock_node)
        wrapped_spec = _wrap_node_with_progress(node_spec, "retrieve", queue)

        state = create_initial_state("test-deck")
        state["current_intent"] = "problem"
        state["generated_slides"] = ["thesis"]

        result = await wrapped_spec.runnable.ainvoke(state)

        # Check progress was pushed
        msg = queue.get_nowait()
        assert msg["type"] == "progress"
        assert msg["phase"] == "retrieve"
        assert msg["intent"] == "problem"
        assert msg["slides_ready"] == 1
        assert msg["deck_id"] == "test-deck"

        # Check node still executed
        assert result["result"] is True

    @pytest.mark.asyncio
    async def test_pushes_gate_update_after_node(self):
        """Wrapper pushes gate_update events for new gate results added by the node."""
        queue = asyncio.Queue()

        async def mock_validate_node(state):
            return {
                **state,
                "current_gate_results": state.get("current_gate_results", []) + [
                    {"gate_name": "g3_format", "passed": True, "score": 1.0, "errors": []},
                ],
            }

        node_spec = self._make_node_spec(mock_validate_node)
        wrapped_spec = _wrap_node_with_progress(node_spec, "validate_format", queue)

        state = create_initial_state("test-deck")
        state["current_intent"] = "problem"
        state["generated_slides"] = []
        state["current_gate_results"] = []

        await wrapped_spec.runnable.ainvoke(state)

        # First message: progress event (before node)
        msg1 = queue.get_nowait()
        assert msg1["type"] == "progress"

        # Second message: gate_update (after node)
        msg2 = queue.get_nowait()
        assert msg2["type"] == "gate_update"
        assert msg2["gate_name"] == "g3_format"
        assert msg2["decision"] == "pass"

    @pytest.mark.asyncio
    async def test_gate_update_fail_decision(self):
        """Gate failures are pushed with decision='fail'."""
        queue = asyncio.Queue()

        async def mock_failing_gate(state):
            return {
                **state,
                "current_gate_results": state.get("current_gate_results", []) + [
                    {"gate_name": "g4_novelty", "passed": False, "score": 0.3, "errors": ["Too similar"]},
                ],
            }

        node_spec = self._make_node_spec(mock_failing_gate)
        wrapped_spec = _wrap_node_with_progress(node_spec, "check_novelty", queue)

        state = create_initial_state("test-deck")
        state["current_intent"] = "thesis"
        state["generated_slides"] = ["problem"]
        state["current_gate_results"] = []

        await wrapped_spec.runnable.ainvoke(state)

        # Skip progress event
        queue.get_nowait()
        msg = queue.get_nowait()
        assert msg["type"] == "gate_update"
        assert msg["gate_name"] == "g4_novelty"
        assert msg["decision"] == "fail"

    @pytest.mark.asyncio
    async def test_no_queue_no_push(self):
        """Without a queue, no error occurs."""
        async def mock_node(state):
            return {**state, "done": True}

        node_spec = self._make_node_spec(mock_node)
        wrapped_spec = _wrap_node_with_progress(node_spec, "draft", None)
        result = await wrapped_spec.runnable.ainvoke(
            {"deck_id": "x", "current_intent": "y", "generated_slides": [], "estimated_cost_usd": 0}
        )

        assert result["done"] is True


# =============================================================================
# Test reveal_live.html template rendering
# =============================================================================


class TestRevealLiveTemplate:
    """Tests for reveal_live.html template rendering."""

    def test_template_renders(self):
        """reveal_live.html renders without error."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test Deck",
            title_slide={
                "title": "Test Title",
                "subtitle": "Test Sub",
                "speaker": "Speaker",
                "event": "Event 2026",
            },
            thanks_slide={
                "title": "Thank You",
                "bullets": ["Bullet 1"],
                "speaker_notes": "Thanks notes",
            },
            deck_id="test-123",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "<!DOCTYPE html>" in html
        assert "gen-status-detail" in html
        assert "EventSource" in html
        assert "test-123" in html

    def test_template_includes_live_status_panel(self):
        """Live status panel with slide count and gates is present."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=10,
            initial_slides=[],
            theme_overrides="",
        )

        assert "live-status-panel" in html
        assert "ls-count" in html
        assert "ls-gate" in html
        assert "ls-checkpoint" in html

    def test_template_includes_sse_handlers(self):
        """SSE event handlers are present in the script."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "slide_added" in html
        assert "progress" in html
        assert "gate_update" in html
        assert "error_event" in html
        assert "complete" in html

    def test_template_includes_sync_override(self):
        """Reveal.sync() override is present for DOM element tracking."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "Reveal.sync" in html
        assert "currentElement" in html
        assert "indexOf" in html

    def test_template_renders_initial_slides(self):
        """Pre-loaded slides are rendered in the live template."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[
                {"html": '<section class=""><div>Pre-loaded slide</div></section>'},
            ],
            theme_overrides="",
        )

        assert "Pre-loaded slide" in html

    def test_dedup_via_received_intents(self):
        """Client-side dedup set (receivedIntents) is initialized."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "receivedIntents" in html

    def test_template_includes_telemetry_mode(self):
        """Telemetry mode CSS and JS are present in the live template."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "telemetry-mode" in html
        assert "telemetry-pulse" in html
        assert "CONTROL PLANE TELEMETRY" in html
        assert "startTelemetryMode" in html
        assert "fetchAndStartRotation" in html
        assert "/api/stats/" in html

    def test_template_includes_score_color_classes(self):
        """Score color CSS classes are present."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "score-good" in html
        assert "score-mid" in html
        assert "score-low" in html

    def test_template_includes_progress_dots(self):
        """Progress dots container and CSS are present."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "ls-progress-dots" in html
        assert "prog-dot" in html

    def test_template_includes_format_duration(self):
        """formatDuration helper function is present."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "formatDuration" in html

    def test_template_includes_hover_pause(self):
        """Hover-to-pause pointer-events and listeners are present."""
        env = get_jinja_env()
        template = env.get_template("reveal_live.html")

        html = template.render(
            title="Test",
            title_slide={"title": "T", "subtitle": "S", "speaker": "P", "event": "E"},
            thanks_slide={"title": "Thanks", "bullets": [], "speaker_notes": ""},
            deck_id="abc",
            target_slides=15,
            initial_slides=[],
            theme_overrides="",
        )

        assert "pointerEvents" in html
        assert "mouseenter" in html
        assert "mouseleave" in html


# =============================================================================
# Test reveal_base.html still works with blocks
# =============================================================================


class TestRevealBaseBlocks:
    """Test that reveal_base.html blocks don't break the static renderer."""

    def test_static_render_unaffected(self):
        """Static renderer still works with empty blocks."""
        from src.renderer import render_deck_from_slides

        slides = [
            {
                "slide_id": str(uuid4()),
                "slide_no": 2,
                "intent": "problem",
                "title": "Test Slide",
                "bullets": ["A", "B", "C"],
                "speaker_notes": "Notes",
                "citations": [],
            }
        ]

        html = render_deck_from_slides(slides, "Static Test")

        assert "<!DOCTYPE html>" in html
        assert "Test Slide" in html
        assert "<section" in html
        # Should NOT contain live-specific elements
        assert "gen-status-detail" not in html
        assert "EventSource" not in html


# =============================================================================
# Test _save_deck_to_output
# =============================================================================


class TestSaveDeckToOutput:
    """Tests for _save_deck_to_output() -- saves static HTML after live generation."""

    @pytest.fixture(autouse=True)
    def _reset_config(self):
        """Save and restore _config and sse_clients around each test."""
        original = dict(_config)
        original_clients = list(sse_clients)
        yield
        _config.update(original)
        sse_clients.clear()
        sse_clients.extend(original_clients)

    @pytest.mark.asyncio
    async def test_saves_deck_on_complete(self, tmp_path):
        """Deck is rendered and written to output directory with <date>_<time>_<topic>.html name."""
        deck_id = str(uuid4())
        _config["deck_id"] = deck_id
        _config["save_deck"] = True
        _config["theme"] = "dark"
        _config["topic"] = "Postgres as AI Server"

        fake_html = "<html>Complete deck</html>"
        with patch("src.server.render_deck", new_callable=AsyncMock, return_value=fake_html) as mock_render, \
             patch("src.server.export_html") as mock_export:
            await _save_deck_to_output()

            mock_render.assert_called_once()
            mock_export.assert_called_once()
            # Verify filename follows <date>_<time>_<topic>.html convention
            call_args = mock_export.call_args
            assert call_args[0][0] == fake_html
            filename = str(call_args[0][1].name)
            assert filename.endswith(".html")
            assert "postgres_as_ai_server" in filename
            # Starts with YYYYMMDD_HHMMSS pattern
            assert len(filename.split("_")) >= 4

    @pytest.mark.asyncio
    async def test_skipped_when_save_deck_false(self):
        """No save when save_deck=False (--no-save flag)."""
        _config["deck_id"] = str(uuid4())
        _config["save_deck"] = False

        with patch("src.server.render_deck", new_callable=AsyncMock) as mock_render:
            await _save_deck_to_output()
            mock_render.assert_not_called()

    @pytest.mark.asyncio
    async def test_skipped_when_no_deck_id(self):
        """No save when deck_id is None."""
        _config["deck_id"] = None
        _config["save_deck"] = True

        with patch("src.server.render_deck", new_callable=AsyncMock) as mock_render:
            await _save_deck_to_output()
            mock_render.assert_not_called()

    @pytest.mark.asyncio
    async def test_notifies_sse_clients(self):
        """SSE clients receive a deck_saved event."""
        deck_id = str(uuid4())
        _config["deck_id"] = deck_id
        _config["save_deck"] = True
        _config["theme"] = "dark"
        _config["topic"] = "Test Topic"

        client_queue = asyncio.Queue()
        sse_clients.append(client_queue)

        with patch("src.server.render_deck", new_callable=AsyncMock, return_value="<html></html>"), \
             patch("src.server.export_html"):
            await _save_deck_to_output()

        event = client_queue.get_nowait()
        assert event["type"] == "deck_saved"
        assert "path" in event["data"]

    @pytest.mark.asyncio
    async def test_handles_render_error_gracefully(self):
        """Render failure is logged, not raised."""
        _config["deck_id"] = str(uuid4())
        _config["save_deck"] = True
        _config["theme"] = "dark"
        _config["topic"] = "Failing Topic"

        with patch("src.server.render_deck", new_callable=AsyncMock, side_effect=RuntimeError("DB gone")), \
             patch("src.server.logger") as mock_logger:
            # Should NOT raise
            await _save_deck_to_output()
            mock_logger.error.assert_called_once()

    @pytest.mark.asyncio
    async def test_uses_configured_theme(self):
        """render_deck is called with the configured theme."""
        deck_id = str(uuid4())
        _config["deck_id"] = deck_id
        _config["save_deck"] = True
        _config["theme"] = "postgres"
        _config["topic"] = "Theme Test"

        with patch("src.server.render_deck", new_callable=AsyncMock, return_value="<html></html>") as mock_render, \
             patch("src.server.export_html"):
            await _save_deck_to_output()

        # Second positional or keyword arg should be theme="postgres"
        _, kwargs = mock_render.call_args
        assert kwargs.get("theme") == "postgres"


# =============================================================================
# Test /api/stats/{deck_id} telemetry endpoint
# =============================================================================


class TestSlideStatsEndpoint:
    """Tests for the /api/stats/{deck_id} telemetry endpoint."""

    @pytest.fixture(autouse=True)
    def _reset_cache(self):
        """Clear the deck stats cache between tests."""
        import src.server as srv
        old_cache = srv._deck_stats_cache
        srv._deck_stats_cache = None
        yield
        srv._deck_stats_cache = old_cache

    def _mock_conn(self, fetchrow_map=None, fetchval_map=None, fetch_map=None):
        """Build a mock async connection with configurable query responses."""
        conn = AsyncMock()

        fetchrow_results = list((fetchrow_map or {}).values())
        fetchval_results = list((fetchval_map or {}).values())
        fetch_results = list((fetch_map or {}).values())

        conn.fetchrow = AsyncMock(side_effect=fetchrow_results if fetchrow_results else [None])
        conn.fetchval = AsyncMock(side_effect=fetchval_results if fetchval_results else [0])
        conn.fetch = AsyncMock(side_effect=fetch_results if fetch_results else [[]])
        return conn

    @pytest.mark.asyncio
    async def test_invalid_deck_id_returns_400(self):
        """Invalid UUID returns 400."""
        resp = await slide_stats("not-a-uuid", slide_no=None)
        assert resp.status_code == 400

    @pytest.mark.asyncio
    async def test_deck_stats_returned(self):
        """Deck-wide stats are returned and cached."""
        deck_id = str(uuid4())

        started = datetime(2026, 2, 27, 1, 0, 0)
        completed = started + timedelta(minutes=3, seconds=14)

        mock_conn = AsyncMock()
        # fetchrow calls: health, coverage, top_failure, top_source, run
        mock_conn.fetchrow = AsyncMock(side_effect=[
            # v_deck_health
            {"slide_count": 16, "total_retries": 5, "avg_retries_per_slide": 0.31,
             "total_gate_failures": 8, "slides_with_failures": 4, "completion_pct": 100.0},
            # v_deck_coverage
            {"covered_intents": 16, "total_slides": 16, "missing": []},
            # v_gate_failures top
            {"gate_name": "g4_novelty", "occurrence_count": 3},
            # v_top_sources top
            {"doc_title": "pgvector docs", "citation_count": 12},
            # generation_run (with timing columns)
            {"llm_calls": 20, "prompt_tokens": 30000, "completion_tokens": 15000,
             "embedding_tokens": 5000, "estimated_cost_usd": 0.42,
             "started_at": started, "completed_at": completed},
        ])
        # fetchval calls: total_gates, total_passes, doc_count, chunk_count, avg_citation_count
        mock_conn.fetchval = AsyncMock(side_effect=[100, 92, 23, 847, 3.5])

        with patch("src.server.get_connection") as mock_gc:
            mock_gc.return_value.__aenter__ = AsyncMock(return_value=mock_conn)
            mock_gc.return_value.__aexit__ = AsyncMock(return_value=False)
            result = await slide_stats(deck_id, slide_no=None)

        assert "deck" in result
        d = result["deck"]
        assert d["total_gate_checks"] == 100
        assert d["pass_rate"] == 92.0
        assert d["total_retries"] == 5
        assert d["doc_count"] == 23
        assert d["chunk_count"] == 847
        assert d["top_source"]["title"] == "pgvector docs"
        assert d["total_gen_seconds"] == 194.0
        assert 0 <= d["health_score"] <= 100
        assert isinstance(d["health_score"], int)
        assert "deck_averages" in d
        assert d["deck_averages"]["avg_retry_count"] == 0.31
        assert d["deck_averages"]["avg_citation_count"] == 3.5
        assert "slide" not in result

    @pytest.mark.asyncio
    async def test_slide_stats_returned_with_slide_no(self):
        """Per-slide stats are returned when slide_no is provided."""
        deck_id = str(uuid4())
        import src.server as srv
        # Pre-populate cache to skip deck-wide queries
        srv._deck_stats_cache = {
            "deck_id": deck_id,
            "total_gate_checks": 50, "total_passes": 45, "pass_rate": 90.0,
            "total_retries": 3, "total_gate_failures": 5, "slide_count": 16,
            "completion_pct": 100.0, "covered_intents": 16, "missing_intents": [],
            "top_failure_gate": None, "top_source": None,
            "llm_calls": 0, "prompt_tokens": 0, "completion_tokens": 0,
            "embedding_tokens": 0, "estimated_cost_usd": 0, "doc_count": 0, "chunk_count": 0,
            "total_gen_seconds": 120.0, "health_score": 85,
            "deck_averages": {"avg_retry_count": 0.2, "avg_gate_failures": 0.3, "avg_citation_count": 2.5},
        }

        mock_conn = AsyncMock()
        mock_conn.fetchrow = AsyncMock(side_effect=[
            # slide row
            {"intent": "problem", "slide_type": "bullets", "title": "The Problem",
             "retry_count": 2, "citations": [{"chunk_id": "c1", "title": "RAG Guide"}]},
            # top fail reason
            {"gate_name": "g4_novelty", "reason": "too similar to slide 3"},
        ])
        # fetchval calls: fail_count, pass_count, gen_seconds
        from decimal import Decimal
        mock_conn.fetchval = AsyncMock(side_effect=[3, 5, Decimal("4.23")])
        mock_conn.fetch = AsyncMock(return_value=[
            {"gate_name": "g4_novelty", "score": 0.82},
            {"gate_name": "g2.5_grounding", "score": 0.91},
        ])

        with patch("src.server.get_connection") as mock_gc:
            mock_gc.return_value.__aenter__ = AsyncMock(return_value=mock_conn)
            mock_gc.return_value.__aexit__ = AsyncMock(return_value=False)
            result = await slide_stats(deck_id, slide_no=2)

        assert "slide" in result
        s = result["slide"]
        assert s["slide_no"] == 2
        assert s["gate_failures"] == 3
        assert s["gate_passes"] == 5
        assert s["retry_count"] == 2
        assert s["citation_count"] == 1
        assert s["top_cited_source"] == "RAG Guide"
        assert s["top_fail_reason"]["gate_name"] == "g4_novelty"
        assert "g4_novelty" in s["gate_scores"]
        assert s["gen_seconds"] == pytest.approx(4.23)

    @pytest.mark.asyncio
    async def test_cache_reused_on_second_call(self):
        """Deck stats cache is reused for the same deck_id."""
        deck_id = str(uuid4())
        import src.server as srv
        srv._deck_stats_cache = {
            "deck_id": deck_id,
            "total_gate_checks": 99, "total_passes": 90, "pass_rate": 90.9,
            "total_retries": 2, "total_gate_failures": 9, "slide_count": 16,
            "completion_pct": 100.0, "covered_intents": 16, "missing_intents": [],
            "top_failure_gate": None, "top_source": None,
            "llm_calls": 0, "prompt_tokens": 0, "completion_tokens": 0,
            "embedding_tokens": 0, "estimated_cost_usd": 0, "doc_count": 10, "chunk_count": 500,
            "total_gen_seconds": 90.0, "health_score": 88,
            "deck_averages": {"avg_retry_count": 0.1, "avg_gate_failures": 0.5, "avg_citation_count": 3.0},
        }

        # No DB mock needed — should use cache
        result = await slide_stats(deck_id, slide_no=None)
        assert result["deck"]["total_gate_checks"] == 99
        assert result["deck"]["doc_count"] == 10

    @pytest.mark.asyncio
    async def test_gen_seconds_none_for_single_gate_entry(self):
        """gen_seconds is None when gate_log returns 0 (single entry)."""
        deck_id = str(uuid4())
        import src.server as srv
        srv._deck_stats_cache = {
            "deck_id": deck_id,
            "total_gate_checks": 10, "total_passes": 10, "pass_rate": 100.0,
            "total_retries": 0, "total_gate_failures": 0, "slide_count": 5,
            "completion_pct": 100.0, "covered_intents": 5, "missing_intents": [],
            "top_failure_gate": None, "top_source": None,
            "llm_calls": 0, "prompt_tokens": 0, "completion_tokens": 0,
            "embedding_tokens": 0, "estimated_cost_usd": 0, "doc_count": 0, "chunk_count": 0,
            "total_gen_seconds": None, "health_score": 90,
            "deck_averages": {"avg_retry_count": 0.0, "avg_gate_failures": 0.0, "avg_citation_count": 0.0},
        }

        mock_conn = AsyncMock()
        mock_conn.fetchrow = AsyncMock(side_effect=[
            {"intent": "thesis", "slide_type": "statement", "title": "Thesis",
             "retry_count": 0, "citations": []},
            None,  # no fail reason
        ])
        mock_conn.fetchval = AsyncMock(side_effect=[0, 1, None])  # fail, pass, gen_seconds=None
        mock_conn.fetch = AsyncMock(return_value=[])

        with patch("src.server.get_connection") as mock_gc:
            mock_gc.return_value.__aenter__ = AsyncMock(return_value=mock_conn)
            mock_gc.return_value.__aexit__ = AsyncMock(return_value=False)
            result = await slide_stats(deck_id, slide_no=1)

        assert result["slide"]["gen_seconds"] is None

    @pytest.mark.asyncio
    async def test_total_gen_seconds_none_when_incomplete(self):
        """total_gen_seconds is None when completed_at is null (in-progress run)."""
        deck_id = str(uuid4())
        started = datetime(2026, 2, 27, 1, 0, 0)

        mock_conn = AsyncMock()
        mock_conn.fetchrow = AsyncMock(side_effect=[
            {"slide_count": 5, "total_retries": 0, "avg_retries_per_slide": 0.0,
             "total_gate_failures": 0, "slides_with_failures": 0, "completion_pct": 80.0},
            {"covered_intents": 4, "total_slides": 5, "missing": ["takeaways"]},
            None, None,
            {"llm_calls": 10, "prompt_tokens": 5000, "completion_tokens": 2000,
             "embedding_tokens": 1000, "estimated_cost_usd": 0.10,
             "started_at": started, "completed_at": None},
        ])
        mock_conn.fetchval = AsyncMock(side_effect=[20, 20, 5, 100, 2.0])

        with patch("src.server.get_connection") as mock_gc:
            mock_gc.return_value.__aenter__ = AsyncMock(return_value=mock_conn)
            mock_gc.return_value.__aexit__ = AsyncMock(return_value=False)
            result = await slide_stats(deck_id, slide_no=None)

        assert result["deck"]["total_gen_seconds"] is None

    @pytest.mark.asyncio
    async def test_health_score_bounded(self):
        """health_score is an integer between 0 and 100."""
        deck_id = str(uuid4())
        started = datetime(2026, 2, 27, 1, 0, 0)
        completed = started + timedelta(seconds=60)

        mock_conn = AsyncMock()
        mock_conn.fetchrow = AsyncMock(side_effect=[
            {"slide_count": 10, "total_retries": 0, "avg_retries_per_slide": 0.0,
             "total_gate_failures": 0, "slides_with_failures": 0, "completion_pct": 100.0},
            {"covered_intents": 10, "total_slides": 10, "missing": []},
            None, None,
            {"llm_calls": 10, "prompt_tokens": 5000, "completion_tokens": 2000,
             "embedding_tokens": 1000, "estimated_cost_usd": 0.10,
             "started_at": started, "completed_at": completed},
        ])
        mock_conn.fetchval = AsyncMock(side_effect=[50, 50, 10, 200, 3.0])

        with patch("src.server.get_connection") as mock_gc:
            mock_gc.return_value.__aenter__ = AsyncMock(return_value=mock_conn)
            mock_gc.return_value.__aexit__ = AsyncMock(return_value=False)
            result = await slide_stats(deck_id, slide_no=None)

        hs = result["deck"]["health_score"]
        assert isinstance(hs, int)
        assert 0 <= hs <= 100

    @pytest.mark.asyncio
    async def test_deck_averages_keys(self):
        """deck_averages contains all three expected keys."""
        deck_id = str(uuid4())
        started = datetime(2026, 2, 27, 1, 0, 0)
        completed = started + timedelta(seconds=90)

        mock_conn = AsyncMock()
        mock_conn.fetchrow = AsyncMock(side_effect=[
            {"slide_count": 8, "total_retries": 4, "avg_retries_per_slide": 0.5,
             "total_gate_failures": 6, "slides_with_failures": 3, "completion_pct": 100.0},
            {"covered_intents": 8, "total_slides": 8, "missing": []},
            None, None,
            {"llm_calls": 15, "prompt_tokens": 10000, "completion_tokens": 5000,
             "embedding_tokens": 2000, "estimated_cost_usd": 0.20,
             "started_at": started, "completed_at": completed},
        ])
        mock_conn.fetchval = AsyncMock(side_effect=[40, 34, 12, 400, 4.2])

        with patch("src.server.get_connection") as mock_gc:
            mock_gc.return_value.__aenter__ = AsyncMock(return_value=mock_conn)
            mock_gc.return_value.__aexit__ = AsyncMock(return_value=False)
            result = await slide_stats(deck_id, slide_no=None)

        avgs = result["deck"]["deck_averages"]
        assert "avg_retry_count" in avgs
        assert "avg_gate_failures" in avgs
        assert "avg_citation_count" in avgs
        assert avgs["avg_retry_count"] == 0.5
        assert avgs["avg_gate_failures"] == 6 / 8
        assert avgs["avg_citation_count"] == 4.2


# =============================================================================
# Test consume_progress race condition fix
# =============================================================================


class TestConsumeProgressComplete:
    """Tests that consume_progress injects authoritative slide count on complete."""

    @pytest.fixture(autouse=True)
    def _reset_config(self):
        original = dict(_config)
        original_clients = list(sse_clients)
        yield
        _config.update(original)
        sse_clients.clear()
        sse_clients.extend(original_clients)

    @pytest.mark.asyncio
    async def test_complete_event_includes_slides_ready(self):
        """Complete event includes authoritative slides_ready from DB."""
        deck_id = str(uuid4())
        _config["deck_id"] = deck_id
        _config["target_slides"] = 15
        _config["save_deck"] = False

        q = asyncio.Queue()
        server_mod.progress_queue = q

        client_queue = asyncio.Queue()
        sse_clients.append(client_queue)

        await q.put({"type": "complete", "deck_id": deck_id})

        with patch("src.server._count_slides", new_callable=AsyncMock, return_value=15):
            await consume_progress()

        event = client_queue.get_nowait()
        assert event["type"] == "complete"
        assert event["data"]["slides_ready"] == 15
        assert event["data"]["total"] == 15

    @pytest.mark.asyncio
    async def test_complete_fixes_stale_count(self):
        """Even if SSE count was behind, complete carries the real DB count."""
        deck_id = str(uuid4())
        _config["deck_id"] = deck_id
        _config["target_slides"] = 15
        _config["save_deck"] = False

        q = asyncio.Queue()
        server_mod.progress_queue = q

        client_queue = asyncio.Queue()
        sse_clients.append(client_queue)

        await q.put({"type": "complete", "deck_id": deck_id})

        with patch("src.server._count_slides", new_callable=AsyncMock, return_value=14):
            await consume_progress()

        event = client_queue.get_nowait()
        assert event["data"]["slides_ready"] == 14
